### create a new user

POST http://localhost:3000/auth/signup
Content-type: application/json

{
    "email": "abc@example.com",
    "password": "sfsfs"
    
}

### find a user of particular given id

GET http://localhost:3000/auth/1

### find all users of given email

GET http://localhost:3000/auth?email=abc@example.com
